/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StableMonitorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkRisk"
      | "checkTotalSupplyRisk"
      | "confidentialProtocolId"
      | "getBalance"
      | "getIssuer"
      | "getRiskThreshold"
      | "getRiskThresholdForCaller"
      | "getTotalSupply"
      | "hasSufficientBalance"
      | "issue"
      | "performRiskCheck"
      | "transfer"
      | "updateRiskThreshold"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Issuance" | "RiskCheck" | "Transfer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkRisk",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkTotalSupplyRisk",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getIssuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRiskThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskThresholdForCaller",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasSufficientBalance",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issue",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "performRiskCheck",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRiskThreshold",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "checkRisk", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkTotalSupplyRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getIssuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRiskThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskThresholdForCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSufficientBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "performRiskCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRiskThreshold",
    data: BytesLike
  ): Result;
}

export namespace IssuanceEvent {
  export type InputTuple = [user: AddressLike, handle: BytesLike];
  export type OutputTuple = [user: string, handle: string];
  export interface OutputObject {
    user: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskCheckEvent {
  export type InputTuple = [user: AddressLike, riskFlagHandle: BytesLike];
  export type OutputTuple = [user: string, riskFlagHandle: string];
  export interface OutputObject {
    user: string;
    riskFlagHandle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    handle: BytesLike
  ];
  export type OutputTuple = [from: string, to: string, handle: string];
  export interface OutputObject {
    from: string;
    to: string;
    handle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StableMonitor extends BaseContract {
  connect(runner?: ContractRunner | null): StableMonitor;
  waitForDeployment(): Promise<this>;

  interface: StableMonitorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkRisk: TypedContractMethod<[user: AddressLike], [string], "nonpayable">;

  checkTotalSupplyRisk: TypedContractMethod<[], [string], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getBalance: TypedContractMethod<[user: AddressLike], [string], "view">;

  getIssuer: TypedContractMethod<[], [string], "view">;

  getRiskThreshold: TypedContractMethod<[], [string], "view">;

  getRiskThresholdForCaller: TypedContractMethod<[], [string], "nonpayable">;

  getTotalSupply: TypedContractMethod<[], [string], "view">;

  hasSufficientBalance: TypedContractMethod<
    [user: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [string],
    "nonpayable"
  >;

  issue: TypedContractMethod<
    [user: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [void],
    "nonpayable"
  >;

  performRiskCheck: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [void],
    "nonpayable"
  >;

  updateRiskThreshold: TypedContractMethod<
    [newThreshold: BytesLike, newThresholdProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkRisk"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "checkTotalSupplyRisk"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getIssuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRiskThreshold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRiskThresholdForCaller"
  ): TypedContractMethod<[], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "getTotalSupply"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasSufficientBalance"
  ): TypedContractMethod<
    [user: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issue"
  ): TypedContractMethod<
    [user: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "performRiskCheck"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike, amountProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateRiskThreshold"
  ): TypedContractMethod<
    [newThreshold: BytesLike, newThresholdProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Issuance"
  ): TypedContractEvent<
    IssuanceEvent.InputTuple,
    IssuanceEvent.OutputTuple,
    IssuanceEvent.OutputObject
  >;
  getEvent(
    key: "RiskCheck"
  ): TypedContractEvent<
    RiskCheckEvent.InputTuple,
    RiskCheckEvent.OutputTuple,
    RiskCheckEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;

  filters: {
    "Issuance(address,bytes32)": TypedContractEvent<
      IssuanceEvent.InputTuple,
      IssuanceEvent.OutputTuple,
      IssuanceEvent.OutputObject
    >;
    Issuance: TypedContractEvent<
      IssuanceEvent.InputTuple,
      IssuanceEvent.OutputTuple,
      IssuanceEvent.OutputObject
    >;

    "RiskCheck(address,bytes32)": TypedContractEvent<
      RiskCheckEvent.InputTuple,
      RiskCheckEvent.OutputTuple,
      RiskCheckEvent.OutputObject
    >;
    RiskCheck: TypedContractEvent<
      RiskCheckEvent.InputTuple,
      RiskCheckEvent.OutputTuple,
      RiskCheckEvent.OutputObject
    >;

    "Transfer(address,address,bytes32)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
  };
}
